version: '3.8'
services:
  db:
    image: mysql:8.0.21
    privileged: true
    environment:
      # 设置默认数据库和root默认密码,如果宿主机中/var/lib/mysql已经存在,这两个设置都不会生效
      - MYSQL_ROOT_PASSWORD=root
    volumes:
#      - "/var/lib/mysql:/var/lib/mysql" # 挂载宿主机的mysql数据到docker中
      - ./db/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./db:/docker-entrypoint-initdb.d/:ro
    # 端口映射,格式 宿主机端口:容器端口
    ports:
      - "13306:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    entrypoint: /bin/sh
    command: -c "/app/start.sh app"
    depends_on:
      - db
    ports:
      - "8000:8000"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    entrypoint: /bin/sh
    command: -c "/app/start.sh celery-worker"
    depends_on:
      - db
      - mq

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    entrypoint: /bin/sh
    command: -c "/app/start.sh celery-beat"
    depends_on:
      - mq
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./templates:/www/FasterRunner/templates
      - ./static:/www/FasterRunner/static
    ports:
      - "80:80"
    depends_on:
      - app

  mq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"


